name: release
on:
  workflow_dispatch:
  push:
    branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          corepack enable
          pnpm i --frozen-lockfile
      - name: Test
        run: pnpm lint && pnpm test
      - name: Build
        run: pnpm build
      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
